#!/usr/bin/env bash
#
while read -r l ; do
	a1=$(echo "$l" | cut -d ":" -f 1)
	a4=$(echo "$l" | cut -d ":" -f 4)
	a6=$(echo "$l" | cut -d ":" -f 6)
	a7=$(echo "$l" | cut -d ":" -f 7)
	a3=$(echo "$l" | cut -d ":" -f 3)
	a5=$(echo "$l" | cut -d ":" -f 5)
	a2=$(echo "$l" | cut -d ":" -f 2)
	echo "The user $a1 is part of the $a4 gang, lives in $a6 and rides $a7. $a3's place is protected by the passcode $a2, more info about the user here: $5"
done < "/etc/passwd"
