#!/usr/bin/env bash
#
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM
echo $(pgrep "./10-process_and_pid_file") > /var/run/myscript.pid
while true ; do
	echo "To infinity and beyond"
done

