#!/usr/bin/env bash
#
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
while true ; do
	echo "To infinity and beyond"
done
